#!/bin/bash

# config jenkins
sudo mkdir /var/lib/jenkins/init.groovy.d
sudo cp /tmp/setup.groovy /var/lib/jenkins/init.groovy.d
sudo chown -R jenkins:jenkins /var/lib/jenkins/init.groovy.d
sudo cp /tmp/jenkins-config.yaml /var/lib/jenkins/jenkins.yaml
sudo cat /var/lib/jenkins/jenkins.yaml
sudo chown jenkins:jenkins /var/lib/jenkins/jenkins.yaml

# Install Jenkins CLI
wget http://localhost:8080/jnlpJars/jenkins-cli.jar -P /tmp

# Get the admin password
INITIAL_ADMIN_PASSWORD=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)

# List of recommended plugins
RECOMMENDED_PLUGINS=(
  "ant:latest"
  "antisamy-markup-formatter:latest"
  "build-timeout:latest"
  "cloudbees-folder:latest"
  "configuration-as-code:latest"
  "credentials-binding:latest"
  "email-ext:latest"
  "git:latest"
  "github-branch-source:latest"
  "gradle:latest"
  "ldap:latest"
  "mailer:latest"
  "matrix-auth:latest"
  "pam-auth:latest"
  "pipeline-github-lib:latest"
  "pipeline-stage-view:latest"
  "ssh-slaves:latest"
  "timestamper:latest"
  "workflow-aggregator:latest"
  "ws-cleanup:latest"
  "authorize-project:latest"
)

# Loop through the list of plugins and install each one
for plugin in "${RECOMMENDED_PLUGINS[@]}"; do
  java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ -auth admin:$INITIAL_ADMIN_PASSWORD install-plugin $plugin
done

java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ -auth admin:$INITIAL_ADMIN_PASSWORD restart

sudo sed -i 's/--environ/--environ CADDY_TLSALPN01_DISABLED=true/g' /usr/lib/systemd/system/caddy.service

SECRETS_FILE=/var/lib/jenkins/secrets/secrets.properties 

sudo tee /usr/lib/systemd/system/jenkins.service > /dev/null <<EOF
#
# This file is managed by systemd(1). Do NOT edit this file manually!
# To override these settings, run:
#
#     systemctl edit jenkins
#
# For more information about drop-in files, see:
#
#     https://www.freedesktop.org/software/systemd/man/systemd.unit.html
#

[Unit]
Description=Jenkins Continuous Integration Server
Requires=network.target
After=network.target

[Service]
Type=notify
NotifyAccess=main
ExecStart=/usr/bin/jenkins
Restart=on-failure
SuccessExitStatus=143

# Configures the time to wait for start-up. If Jenkins does not signal start-up
# completion within the configured time, the service will be considered failed
# and will be shut down again. Takes a unit-less value in seconds, or a time span
# value such as "5min 20s". Pass "infinity" to disable the timeout logic.
#TimeoutStartSec=90

# Unix account that runs the Jenkins daemon
# Be careful when you change this, as you need to update the permissions of
# \$JENKINS_HOME, \$JENKINS_LOG, and (if you have already run Jenkins)
# \$JENKINS_WEBROOT.
User=jenkins
Group=jenkins

# Directory where Jenkins stores its configuration and workspaces
Environment="JENKINS_HOME=/var/lib/jenkins"
WorkingDirectory=/var/lib/jenkins

# Location of secrets file
Environment="SECRETS_FILE=$SECRET_FILE"

# Location of the exploded WAR
Environment="JENKINS_WEBROOT=%C/jenkins/war"

# Arguments for the Jenkins JVM
Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.config=/var/lib/jenkins/jenkins.yaml"

# Port to listen on for HTTP requests. Set to -1 to disable.
# To be able to listen on privileged ports (port numbers less than 1024),
# add the CAP_NET_BIND_SERVICE capability to the AmbientCapabilities
# directive below.
Environment="JENKINS_PORT=8080"

[Install]
WantedBy=multi-user.target
EOF

sudo tee -a $SECRETS_FILE > /dev/null <<EOF
USERNAME=$JENKINS_USERNAME
PASSWORD=$JENKINS_PASSWORD
EOF

sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo systemctl daemon-reload
sudo systemctl restart jenkins
