jenkins:
  systemMessage: |
    Welcome to Jenkins!
    This is the Jenkins instance for CSYE 7125 course project.
  numExecutors: 4
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${USERNAME}
          password: ${PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - domain:
          name: 'Global credentials'
          description: 'Global credentials'
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: 'github-credentials'
              username: ${GITHUB_USERNAME}
              password: ${GITHUB_ACCESS_TOKEN}
              description: 'GitHub credentials'
          - usernamePassword:
              scope: GLOBAL
              id: 'docker-credentials'
              username: ${DOCKER_USERNAME}
              password: ${DOCKER_TOKEN}
              description: 'Docker credentials'
          - gitHubApp:
              scope: GLOBAL
              appID: ${GH_APP_ID}
              id: 'github-jenkins-app'
              description: 'GitHub status check Jenkins App'
              owner: 'csye7125-su24-team05'
              privateKey: ${decodeBase64:${GH_APP_PRIVATE_KEY}}

jobs:
  - file: /var/lib/jenkins/pipeline/org/folder.groovy
  - file: /var/lib/jenkins/pipeline/org/release.groovy
  - file: /var/lib/jenkins/pipeline/status-check.groovy
  - file: /var/lib/jenkins/pipeline/org/commit-check.groovy

unclassified:
  location:
    url: 'https://jenkins.nexflare.me'

  githubpluginconfig:
    configs:
      - apiUrl: 'https://api.github.com'
        manageHooks: true
        credentialsId: 'github-credentials'
        name: 'github'
