jenkins:
  systemMessage: "Welcome to Jenkins ${USERNAME}!"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${USERNAME}
          password: ${PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - domain:
          name: "Global credentials"
          description: "Global credentials"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-credentials"
              username: ${GITHUB_USERNAME}
              password: ${GITHUB_ACCESS_TOKEN}
              description: "GitHub credentials"
          - usernamePassword:
              scope: GLOBAL
              id: "docker-credentials"
              username: ${DOCKER_USERNAME}
              password: ${DOCKER_TOKEN}
              description: "Docker credentials"

jobs:
  - script: >
      pipelineJob('docker-build-and-push') {
        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url('https://github.com/csye7125-su24-team05/static-site')
                            credentials('github-credentials')
                        }
                        branches('*/main')
                        extensions {
                            cleanBeforeCheckout()
                        }
                    }
                }
                scriptPath('Jenkinsfile') // Path to your Jenkinsfile in the repo
            }
        }
        triggers {
          githubPush()
        }
      }
  - script: >
      multibranchPipelineJob('status-check') {
        branchSources {
          github {
            id('static-site-pr-check')
            repoOwner('csye7125-su24-team05')
            repository('static-site')
            buildForkPRHead(true)
            buildForkPRMerge(false)
            buildOriginBranchWithPR(false)
            buildOriginBranch(false)
            scanCredentialsId('github-credentials')
            checkoutCredentialsId('github-credentials')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath('Jenkinsfile-pr')
          }
        }
      }

unclassified:
  location:
    url: "https://jenkins.nexflare.me"

  githubpluginconfig:
    configs:
      - apiUrl: "https://api.github.com"
        manageHooks: true
        credentialsId: "github-credentials"
        name: "github"
